
EXECUTABLE_FORMAT_PREPEND=
EXECUTABLE_FORMAT_APPEND=

ifeq ($(OS),Windows_NT)
	SHELL=C:/Windows/System32/cmd.exe
	EXECUTABLE_FORMAT_APPEND=.exe
	CLEAR_COMMAND=del
	PATH_SEPARATOR=\\

else
	CLEAR_COMMAND=rm
	PATH_SEPARATOR=/
endif

EXECUTABLE_FORMAT_PREPEND=.$(PATH_SEPARATOR)



MAIN_DIR=
ifndef MAIN_DIR
	MAIN_DIR=.
endif
EXECUTABLE_MAIN_PATH=$(MAIN_DIR)$(PATH_SEPARATOR)compiler$(EXECUTABLE_FORMAT_APPEND)


TEST_DIR=test
ifndef TEST_DIR
	TEST_DIR=.
endif
EXECUTABLE_TEST_PATH=$(TEST_DIR)$(PATH_SEPARATOR)test$(EXECUTABLE_FORMAT_APPEND)




CC=clang++ 
CFLAGS=--std=c++17



all: main


build_main:
	$(CC) $(CFLAGS) '$(MAIN_DIR)$(PATH_SEPARATOR)compiler.cpp' -o '$(EXECUTABLE_MAIN_PATH)' -I src


main: build_main
	$(EXECUTABLE_MAIN)


build_test:
	$(CC) $(CFLAGS) $(TEST_DIR)$(PATH_SEPARATOR)test.cpp -o $(EXECUTABLE_TEST_PATH) -I src

test: build_test
	$(EXECUTABLE_TEST_PATH)



remove_test_executable:
	$(CLEAR_COMMAND) "$(EXECUTABLE_TEST_PATH)"
